make:
	g++ -o a.e main.cpp Graph.cpp Station.cpp Stretch.cpp Point.cpp Area.cpp Display.cpp Graphics.cpp SaveAndLoad.cpp Present.cpp

damage:
	g++ -o final main2.cpp Graph.cpp Station.cpp Stretch.cpp Point.cpp Area.cpp Display.cpp Graphics.cpp SaveAndLoad.cpp Present.cpp Parser.cpp Menu.cpp